const TYPES = {
  'GET_CHARACTERS': 'GET_CHARACTERS',
  'GET_ONE_CHARACTER': 'GET_ONE_CHARACTER',
  'LOAD_CHARACTERS':'UPDATE_CHARACTERS',
  'GET_FAVORITES':'GET_FAVORITES',
  'ADD_FAVORITE': 'ADD_FAVORITE',
  'REMOVE_FAVORITE': 'REMOVE_FAVORITE',
  'CHANGE_THEME': 'CHANGE_THEME',
  'RESET_PAGE': 'RESET_PAGE'
};


export default TYPES;

